### PR TITLE
compile with SDCC 4.2.0

### PR DESCRIPTION
**Pull request by macpijan**
4.5.0 used to fail with:

src/board/system76/common/smfi.c:209: error 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
make: *** [src/arch/8051/toolchain.mk:54: build/novacustom/v540tu/2026-02-27_41e94a7/board/system76/common/smfi.rel] Error 1
Failed to build EC firmware : (2)

Tried to build in: https://github.com/Dasharo/ec-sdk/pull/2

Switching to 4.2.0 results in successfull build.

### CODE REVIEW

**Review by mkopec — APPROVED** [review]

**Comment by macpijan** [comment]
We use `:main` tag here, possibly it alters older builds: https://github.com/Dasharo/ec/blob/master/build.sh#L74 when merged and uploaded under `:main` tag ?

**Comment by macpijan** [comment]
@mkopec 

Problems before merging this:
1. We break reproducibility of older releases possibly: https://github.com/Dasharo/ec/pull/82#issuecomment-3973647461 ? But maybe there is no other way around that if we use moving tag in a build script.

2. We have a build problem for V56, not for V54. Reported here in heads: https://app.circleci.com/pipelines/github/tlaurion/heads/3546/workflows/6e2fa61e-dffd-45d7-bee3-ede1fa1e7ebc/jobs/83042

Can be reproduced locally as well. It does not reproduce on `maste` so I guess it's the compiler change being the issue here?

```
  CC        novacustom/v560tu/2026-02-27_ad7e15c/ec/ite/ps2.rel
  CC        novacustom/v560tu/2026-02-27_ad7e15c/ec/ite/signature.rel
  CC        novacustom/v560tu/2026-02-27_ad7e15c/keyboard/system76/15in_102/keymap/micmute.rel
  LINK      novacustom/v560tu/2026-02-27_ad7e15c/ec.ihx
?ASlink-Error-Could not get 5 consecutive bytes in internal RAM for area OSEG.
?ASlink-Error-Could not get 4 consecutive bytes in internal RAM for area OSEG.
make: *** [src/arch/8051/toolchain.mk:42: build/novacustom/v560tu/2026-02-27_ad7e15c/ec.ihx] Error 1
Failed to build EC firmware : (2)
```

**Comment by mkopec** [comment]
@macpijan I pushed some fixes to free up space in DSEG by marking more functions as `__reentrant`.

**Comment by tlaurion** [comment]
Was https://github.com/Dasharo/heads/commit/fe3d278f6406f446e3099b96a6dc504a539a8a9e flashing EC for you on v560tu @mkopec? Can't reproduce : stays in old  same version on Circleci builds at https://github.com/tlaurion/heads/commit/83890d9d1c53ec3da0ca661bdde8fa2a79f3fc75

**Comment by mkopec** [comment]
@tlaurion just to check, can you power on the laptop with the AC adapter connected? That should trigger the update. It won't update if there's no power adapter plugged in

**Comment by tlaurion** [comment]
> @tlaurion just to check, can you power on the laptop with the AC adapter connected? That should trigger the update. It won't update if there's no power adapter plugged in

I flashed prior build with USB-C charger connected. Plugged AC charger, rebooted, didn't update EC. **Seems like it's applied only on first reboot after flash just like memory training?**

Flashing https://output.circle-artifacts.com/output/job/ec338040-b1bb-4195-84f9-247f5e05c46f/artifacts/0/build/x86/novacustom-v560tu/heads-novacustom-v560tu-v0.2.1-2958-g555bd9a.zip with AC power connected.

**Fan went full speed, on reboot. Then laptop powered off, just like when EC got flashed for v540tu.
This needs documentation (both AC power needed, not USB-C powered, and poweroff with full speed of fan prior of shutdown).**

On reboot, System Info shows:
`EC_VER: 2026-03-12_d198b64` 

Works!
